### ISSUE TITLE
Graceful Shutdown and Log Draining

### ISSUE THREAD

**Issue by kevinmstephens** [hapijs/good-http#26]
Howdy, this is a question of best practice more than anything.

When I do a `server.stop` I think `http-good` will send whatever is left in its queue. However there is no way to know when the final request to the log server has finished to actually exit the process based on the lack of callback here: https://github.com/hapijs/good-http/blob/master/lib/index.js#L113

So what is best practice? Should I just give a "reasonable" amount of time for this to wrap up?

I guess I could use `good-broadcast` for more deterministic behavior if `good-file` has a way to know when logs are drained to the file system.

Thanks for the help!

**Comment by arb** [comment]
Great question. As of right NOW, when the "end" event occurs, good-http attempts to drain anything left in the buffer. As you've pointed out, there isn't a callback here to know when or even if the request has finished. I'd just give it a reasonable time as you've suggested.

In good version 7, this reporter will have a `stop` function that will be called when the server is shutting down so any "last ditch" efforts can be done there. Check out https://github.com/hapijs/good/blob/master/API.md#reporter-lifecycle for more details.

**Comment by kevinmstephens** [comment]
Sounds good. I'm satisfied if you want to close or do whatever with this ticket. Thanks for the fast response.
