### ISSUE TITLE
delegate to child process?

### ISSUE THREAD

**Issue by dylancwood** [hapijs/good-http#35]
It might be out of the scope of this package, but I am curious to know your thoughts on delegating log processing/shipping to a child process. It certainly increases complexity, but it could also reduce the impact that the reporter has on the performance of an API. 

Here is how I thought it could work:
At server-startup, a child process is forked which will run the good-http reporter. Good will pass all events to the child process via RPC or stdin.

**Comment by Marsup** [comment]
You'd still need to serialize your data to that child process, what do you expect to win doing this ?

**Comment by dylancwood** [comment]
I guess that I don't have a good sense for this yet: We just switched from using good-broadcast to using good-http, and it has really simplified our deployment process :+1:. Unfortunately, we're also seeing a 13% increase in response times after switching to good-http. I can only assume that this is due to good-http taking up some portion of our event loops that previously were used to respond to requests. We have set threshold to 50, however, each request generates multiple events (request, response and info). Based on this, I would estimate that good-http is transmitting every 17 requests or so. 

I don't know if the performance hit that we are seeing is due to connection creation overhead, or event object serialization. I will look into it further. If you have any suggestions for bottleneck-finding, please let me know.

**Comment by dylancwood** [comment]
Ok, I did a little more investigation. 

For those that don't want to read everything below, here's a quick summary:
1. Serialization of large objects currently accounts for about twice as much CPU time as establishing a connection.
2. Delegating to a child process is actually slower (:shakefist: `child_process.send()`).

First, I set up a test hapi server that uses good-http to ship requests to another test server running in a different process. The test server simply responds to get requests with a large string, which it reads from disk. 

Next, I used Apache Bench to load the server both with and without good-http turned on. Unsurprisingly, throughput was 3x higher with good-http turned of (the server without good-http is just a static file server with no logging). 

Finally, I started the server with `node --prof` to profile CPU usage when good-http is turned on. The results are below, but I will summarize here: serialization is taking about 24% of cpu time, and 19% is spent in creating the connection. Additionally, 7% is spent performing join operations, which I think might be due to adding events onto the array of events to be sent by good-http.
```
[Bottom up (heavy) profile]:
  Note: percentage shows a share of a particular caller in the total
  amount of its parent calls.
  Callers occupying less than 2.0% are not shown.

   ticks parent  name
   1276   65.9%  /Users/dwood4/.nvm/versions/node/v4.4.0/bin/node
   1149   90.0%    /Users/dwood4/.nvm/versions/node/v4.4.0/bin/node
    276   24.0%      LazyCompile: *JSONSerialize native json.js:120:23
    236   85.5%        LazyCompile: *SerializeObject native json.js:75:25
    236  100.0%          LazyCompile: *JSONSerialize native json.js:120:23
    164   69.5%            LazyCompile: ~SerializeArray native json.js:48:24
     70   29.7%            LazyCompile: *SerializeArray native json.js:48:24
     40   14.5%        LazyCompile: ~SerializeObject native json.js:75:25
     40  100.0%          LazyCompile: *JSONSerialize native json.js:120:23
     40  100.0%            LazyCompile: ~SerializeArray native json.js:48:24
    224   19.5%      LazyCompile: ~Socket._writeGeneric net.js:628:42
    222   99.1%        LazyCompile: ~<anonymous> net.js:635:34
    222  100.0%          LazyCompile: ~g events.js:255:13
    126   56.8%            LazyCompile: ~emitNone events.js:65:18
     96   43.2%            LazyCompile: *emit events.js:117:44
     82    7.1%      LazyCompile: ~byteLength buffer.js:260:20
     51   62.2%        LazyCompile: ~internals.Client.request /Users/dwood4/Documents/Walmart/sandbox/node_modules/good-http/node_modules/wreck/lib/index.js:65:47
     51  100.0%          LazyCompile: ~internals.GoodHttp._sendMessages /Users/dwood4/Documents/Walmart/sandbox/node_modules/good-http/lib/index.js:91:55
     44   86.3%            LazyCompile: *<anonymous> /Users/dwood4/Documents/Walmart/sandbox/node_modules/good-http/lib/index.js:71:47
      7   13.7%            LazyCompile: ~<anonymous> /Users/dwood4/Documents/Walmart/sandbox/node_modules/good-http/lib/index.js:71:47
     20   24.4%        LazyCompile: *internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.internals.Payload.size /Users/dwood4/Documents/Walmart/sandbox/           >  \node_modules/hapi/lib/response.js:611:45
     20  100.0%          LazyCompile: ~<anonymous> /Users/dwood4/Documents/Walmart/sandbox/node_modules/hapi/lib/transmit.js:124:27
     20  100.0%            LazyCompile: internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.internals.Response._streamify /Users/dwood4/Documents/Walmart/sandbox/ >  \node_modules/hapi/lib/response.js:484:52
      5    6.1%        LazyCompile: *internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.internals.Payload._read /Users/dwood4/Documents/Walmart/sandbox/          >  \node_modules/hapi/lib/response.js:593:46
      5  100.0%          LazyCompile: *resume_ _stream_readable.js:715:17
      5  100.0%            LazyCompile: nextTickCallbackWith2Args node.js:439:39
      3    3.7%        LazyCompile: ~internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.internals.Payload.size /Users/dwood4/Documents/Walmart/sandbox/           >  \node_modules/hapi/lib/response.js:611:45
      3  100.0%          LazyCompile: ~<anonymous> /Users/dwood4/Documents/Walmart/sandbox/node_modules/hapi/lib/transmit.js:124:27
      3  100.0%            LazyCompile: internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.internals.Response._streamify /Users/dwood4/Documents/Walmart/sandbox/ >  \node_modules/hapi/lib/response.js:484:52
      3    3.7%        LazyCompile: *Readable.push _stream_readable.js:99:35
      3  100.0%          LazyCompile: ~internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.internals.Payload._read /Users/dwood4/Documents/Walmart/sandbox/        >  \node_modules/hapi/lib/response.js:593:46
      1   33.3%            Stub: BinaryOpICWithAllocationSiteStub(ADD_CreateAllocationMementos:String*String->String) {2}
      1   33.3%            LazyCompile: ~resume_ _stream_readable.js:715:17
      1   33.3%            LazyCompile: *resume_ _stream_readable.js:715:17
     81    7.0%      LazyCompile: Join native array.js:102:14
     81  100.0%        LazyCompile: ~InnerArrayJoin native array.js:317:24
     80   98.8%          LazyCompile: *join native array.js:333:19
     37   46.3%            LazyCompile: *SerializeObject native json.js:75:25
     23   28.7%            LazyCompile: ~SerializeArray native json.js:48:24
     16   20.0%            LazyCompile: ~SerializeObject native json.js:75:25
      3    3.8%            LazyCompile: ~Module._nodeModulePaths module.js:188:35

```
To put this further into perspective, I ran another test: I edited my local installed copy of good-http so that it just wrote the JSON, rather than calling `Wreck.request()`. Performance was similar to sending the data over http. 

Finally, I wired up a dummy child process inside good-http, and sent the log data to it over IPC. Performance in this case actually degraded from an average of 62ms per request to over 80ms per request...

Thanks @Marsup for your reply. I'm happy to close this issue now that I have investigated more thoroughly.

**Comment by Marsup** [comment]
I don't think we can avoid serialization, it will always have a cost, but I'm still surprised you'd see a difference between http and broadcast. It could be a bit better if we used json streaming but I'm not sure by how much.
