### ISSUE TITLE
Update depencency

### ISSUE THREAD

**Issue by minustime** [hapijs/good-http#41]
Every version of fast-safe-stringify prior to v1.1.0 has been deprecated, see: https://github.com/davidmarkclements/fast-safe-stringify/issues/4, please update to the latest.

**Comment by Marsup** [comment]
Why didn't you just PR instead ?

**Comment by minustime** [comment]
Sure thing! done.

**Comment by doron2402** [comment]
https://github.com/hapijs/good-http/pull/44
